{% set version = "1.2" %}
{% set build_number = 0 %}
{% set clang_version = "18.1.8" %}

package:
  name: cling
  version: {{ version }}

source:
  url: https://github.com/root-project/cling/archive/v{{ version }}.tar.gz
  sha256: beee8e461424d267ee2dec88b3de57326bc8e3470b4ceae2744de7d3d3aba1eb
  patches:
    # Export all symbols on windows to generate import library
    - patches/0001-Export-all-symbols-on-windows.patch
    # Do not build Jupyter kernel - use xeus-cling instead
    - patches/0002-remove-jupyter.patch
    # Prevent setting sysroot include directory on OS X
    - patches/0003-Drop-compile-time-sysroot.patch
    # Enable redefinitions
    - patches/0004-enable-redefinition-allowed.patch
    # LLVM_REQUIES_EH
    - patches/0005-Set-LLVM_REQUIRES_EH-for-Cling.patch


build:
  number: {{ build_number }}
  skip: true  # [win and vc<14 or aarch64]
  run_exports:
    - {{ pin_subpackage("cling", max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja  # [win]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - clangdev {{ clang_version }} cling_v{{ version }}*
    - zlib
  run:
    # We really depend on the host compiler at runtime:
    #  - the host compiler STL is one to be used.
    #  - it is used by cling's runtime compatibility check.
    - {{ compiler('cxx') }}  # [linux]
    - clangdev {{ clang_version }} cling_v{{ version }}*

test:
  commands:
    - test -f $PREFIX/bin/cling  # [unix]
    - if exist %LIBRARY_PREFIX%\\bin\\libcling.dll (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\\lib\\libcling.lib (exit 0) else (exit 1)  # [win]
    - cling '2+3; 0'
    - cling '#include <vector>'

about:
  dev_url: https://github.com/root-project/cling
  doc_url: https://root.cern.ch/cling
  home: https://root.cern.ch/cling
  license: NCSA OR LGPL-2.1-only
  license_file: LICENSE.TXT
  summary: Cling - The Interactive C++ Interpreter
  description: Cling is an interactive C++ interpreter, built on top of Clang and LLVM compiler infrastructure. Cling realizes the read-eval-print loop (REPL) concept, in order to leverage rapid application development. Implemented as a small extension to LLVM and Clang, the interpreter reuses their strengths such as the praised concise and expressive compiler diagnostics.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
    - chrisburr
