{% set name = "cling" %}
{% set version = "1.0" %}
{% set sha256 = "93252c72bae2a660d9e2c718af18b767a09928078a854b2fcd77f28cc9fa71ae" %}
{% set build_number = 0 %}
{% set clang_version = [9, 0, 1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/root-project/cling/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Export all symbols on windows to generate import library
    - patches/0001-Export-all-symbols-on-windows.patch
    # Do not build Jupyter kernel - use xeus-cling instead
    - patches/0001-remove-jupyter.patch
    - patches/0027-conda-packaging.patch
    # Prevent setting sysroot include directory on OS X
    - patches/0001-Drop-compile-time-sysroot.patch
    # Enable redefinitions
    - patches/enable-redefinition-allowed.patch
    # LLVM_REQUIES_EH
    - patches/0001-Set-LLVM_REQUIRES_EH-for-Cling.patch
    # Fix incorrect dylib interactions
    - patches/0001-Fix-LLVM_DYLIB-usage.patch
    # Install ClingTargets.cmake
    - patches/0001-Fix-ClingTargets.cmake-not-being-installed.patch


build:
  number: {{ build_number }}
  skip: true  # [win and vc<14 or aarch64]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja  # [win]
    - {{ compiler('cxx') }}
    - make
  host:
    - llvmdev {{ clang_version|join('.') }} cling_v{{ version }}*
    - clangdev {{ clang_version|join('.') }} cling_v{{ version }}*
    - zlib
  run:
    # We really depend on the host compiler at runtime:
    #  - the host compiler STL is one to be used.
    #  - it is used by cling's runtime compatibility check.
    - {{ compiler('cxx') }}  # [linux]
    - clangdev {{ clang_version|join('.') }} cling_v{{ version }}*
  run_constrained:
   # For C++14/C++17 headers from GCC 9.5.0 cannot be parsed due to a missing commit:
    # https://github.com/gcc-mirror/gcc/commit/32bbf76e4345a7961445b86a7cfccffa8a287fc1
    - gxx_linux-64 !=9.5.0  # [clangdev == "5.*"] - sysroot_linux-64  # [linux]

test:
  commands:
    - test -f $PREFIX/bin/cling  # [unix]
    - if exist %LIBRARY_PREFIX%\\bin\\libcling.dll (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\\lib\\libcling.lib (exit 0) else (exit 1)  # [win]
    - cling '2+3; 0'
    - cling '#include <vector>'

about:
  dev_url: https://github.com/root-project/cling
  doc_url: https://root.cern.ch/cling
  home: https://root.cern.ch/cling
  license: NCSA OR LGPL-2.1-only
  license_file: LICENSE.TXT
  summary: Cling - The Interactive C++ Interpreter
  description: Cling is an interactive C++ interpreter, built on top of Clang and LLVM compiler infrastructure. Cling realizes the read-eval-print loop (REPL) concept, in order to leverage rapid application development. Implemented as a small extension to LLVM and Clang, the interpreter reuses their strengths such as the
    praised concise and expressive compiler diagnostics.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
    - chrisburr
